### ISSUE TITLE
Could not start Win 10 x64, DLL files missing

### ISSUE THREAD

**Issue by omgitsgela** [wmcbrine/MultiMail#13]
I downloaded and attempted to run the latest version of MultiMail to date, but I had several issues. Firstly, several DLL files were missing. I got prompts for the following files, which I found on another site and put into the same folder as mm.exe:

libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll

After I sourced and added those files to the same directory as the executable, the program would only give this error:

The application was unable to start correctly (0xc000007b)

What have I done wrong?

**Comment by wmcbrine** [comment]
Sorry about that. You didn't do anything wrong; I did -- although I'm going to blame MinGW-w64, for not making it clear what would be dynamically linked. :) (The DLLs you tried, I assume aren't quite the right versions.)

If you would, please remove those DLLs, and try the attached binaries -- mm1.exe is again built with MinGW-w64, but with the "-static" flag; mm2.exe is built with MSVC.
[mm64test.zip](https://github.com/wmcbrine/MultiMail/files/1989859/mm64test.zip)

**Comment by omgitsgela** [comment]
Both versions appear to be working correctly. Thanks! Verified working on Windows 10 x64.

Can you elaborate on the difference between the two versions? Not sure I understand.

**Comment by wmcbrine** [comment]
Different C++ compilers.
