### ISSUE TITLE
version 0.52 missing colors files on make install

### ISSUE THREAD

**Issue by ftoledo** [wmcbrine/MultiMail#17]
please restore the install of colors files at Makefile:
```
    install -m 644 README $(DOCDIR)
    install -d $(DOCDIR)/colors
    cp -a colors/* $(DOCDIR)/colors
```

**Comment by wmcbrine** [comment]
AFAICT, `make install` has never done that, in any released version of MultiMail. So if it did, it would be a new feature, not a restoration.

Why do you want this?

**Comment by ftoledo** [comment]
My faut!, I thought they were installed from original source, but it is a debian patch to upstream makefile

https://packages.debian.org/sid/amd64/multimail/filelist

thanks!

**Comment by ftoledo** [comment]
> Why do you want this?

I think that are good to have example colors files.. I will working on debian package for 0.52.. Maybe will ship these files into the package as 0.49 debian package.
