### ISSUE TITLE
Segmentation fault on Ubuntu and Debian with relatively big QWK files

### ISSUE THREAD

**Issue by cardpuncher** [wmcbrine/MultiMail#32]
Hi,

When I try to view messages from a somewhat big QWK archive with mm, on Ubuntu and Debian I get a segmentation fault. This is true for the version in the repositories (0.49-2build4 on Ubuntu 20.04.3 and 0.49-2+b4 on Debian 11) and also when I compile from the latest 0.52 release tarball on Ubuntu.
For Ubuntu, uname -a returns 
Linux rina-HP-Notebook 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
and for Debian, the same command returns
Linux freedombox 5.10.0-8-armmp-lpae #1 SMP Debian 5.10.46-4 (2021-08-03) armv7l GNU/Linux

The attached screenshots below may give an idea of when this is happening.

The packet type is shown as QWKE. Although it only contains public messages, I'm wary of uploading it here. I could send it via e-mail if necessary.

What am I doing wrong? If I can provide more information, feel free to tell me what to do.

![Screenshot at 2021-08-30 00-07-45](https://user-images.githubusercontent.com/64688741/131265587-ff6f4b01-ce10-4d19-ae73-97a649812823.png)
![Screenshot at 2021-08-30 00-10-41](https://user-images.githubusercontent.com/64688741/131265590-1955396a-7ecb-40f8-91c0-6a880884f826.png)

**Comment by wmcbrine** [comment]
This doesn't tell me much, so yes, please email the packet.

**Comment by wmcbrine** [comment]
Based on the packet you sent, I can say that there's a problem with the *.ndx files. If you delete them, the packet works.

More later...

**Comment by wmcbrine** [comment]
Yeah, the values in the .ndx files increasingly diverge from their correct positions in messages.dat. (The values in .ndx are too low.) I dunno yet how this would arise, but it's a Synchronet-side bug. Meanwhile, you can avoid the problem by setting "IgnoreNDX:" to "Yes" in your MultiMail config.

**Comment by cardpuncher** [comment]
On 30.08.2021 17:59, William McBrine wrote:
> Yeah, the values in the .ndx files increasingly diverge from their
> correct positions in messages.dat. (The values in .ndx are too low.) I
> dunno yet how this would arise, but it's a Synchronet-side bug.

Thank you for looking into this. Should I report the bug to Digital Man,
Synchronet's author, or ping him here on GitHub?

> Meanwhile, you can avoid the problem by setting "IgnoreNDX:" to "Yes" in
> your MultiMail config.

Thanks for the information, indeed it works just fine with that
parameter :) As a feature request, maybe it would be nice if mm could
handle such malformed packets more gracefully than with a segfault.

**Comment by wmcbrine** [comment]
Dude, 99% of the development time on MultiMail was dealing with malformed crap like this. Obviously I've tried to compensate, and I'll continue to do so, but people keep coming up with new ways to screw things up that I hadn't anticipated.

I'll report it myself, but I'm gonna look into it for a little while longer first.

**Comment by wmcbrine** [comment]
It's possible that this: https://gitlab.synchro.net/main/sbbs/-/commit/2bc1d73f7c7e147b909c46946748c0ca5d5c88f2 is the fix? Your packet says 3.17b, but synchro.net has 3.18b, so perhaps Slinky's Place should update.

The patch says it applies only when "both Indexes (NDX files) and vote messages are included in a QWK packet (an unexpected, but valid combination)", which does appear to be the case with your packet. (I have no idea what this voting stuff is, but I see that "voting.dat" is present.)

**Comment by wmcbrine** [comment]
Actually, it looks like the fix came after 3.18b.

**Comment by rswindell** [comment]
I agree, this sounds like an already-fixed issue. And with a normal/sane packet configuration, the problem doesn't happen to begin with (it doesn't really make sense today to include *both* index/NDX files and the voting.dat, though it is a supported combination).

For information on what "this voting stuff is" (just as an FYI), see https://wiki.synchro.net/ref:qwk#votingdat

**Comment by wmcbrine** [comment]
Fixes for my side (c5bb44efeba11e02de5eb625bd50cf3765a47e3f and 77ee98b64201fbbed337c49f7f6deba1465d3e7b)

(Note, you still have to switch to IgnoreNDX mode to actually read the messages in the bad packets. It's tempting to make it the default mode, but... no.)
