### ISSUE TITLE
MultiMail 0.49 is hanging when opening QWK packets higher than 2MB from a Mystic-based BBS

### ISSUE THREAD

**Issue by XBessa** [wmcbrine/MultiMail#4]
Hello, 

I am getting a few user complaints about Multimail 0.49 where:

- They generate a QWK with more than 2MB;
- They download it to their home directory;
- When opening it, MultiMail unpacks the QWK, but hangs. Screen continues black forever;
- Same QWK opens when done so by Blue Wave.

**Comment by wmcbrine** [comment]
I doubt that it's the size -- I've worked with larger packets than that, IIRC -- but maybe some specific content? It would help if I could see one or more of the problem packets. (I can accept email attachments up to 5 MB, or you can upload anonymous FTP to the incoming directory on wmcbrine.com.)

I also need to know the specific platform version(s) of MultiMail and the OS(es) being used.

**Comment by XBessa** [comment]
Hello William,

   Thanks for the reply.

    I am using version 0.49 for Mac OSX. Please find attached the QWK
packet and the .mmailrc file.



2017-03-17 6:01 GMT-03:00 William McBrine <notifications@github.com>:

**Comment by wmcbrine** [comment]
Not the version _you're_ using, the version(s) being used by the people who are complaining. Unless you have the same problem?

I'm not seeing any attachments.

**Comment by XBessa** [comment]
Hello William,

This happened with a user of mine that uses Windows 0.49 release, and I
reproduced into my Mac OS 0.49 release.

I have uploaded to your FTP server the mmail.rc file and the QWK package.

2017-03-17 10:55 GMT-03:00 William McBrine <notifications@github.com>:

**Comment by wmcbrine** [comment]
Thanks, I can reproduce it with that packet. Yeah, there are at least two problems with the packet (errors in both the *.ndx and messages.dat files). It'll take me a little longer to sort out how MultiMail should handle this.

**Comment by wmcbrine** [comment]
OK, I've put in a patch for MultiMail to allow it to read (most of) the bad packet. I also sent a report to the Mystic BBS author.

**Comment by XBessa** [comment]
Thanks a lot! How can I get this patch?

Em dom, 19 de mar de 2017 às 09:49, William McBrine <
notifications@github.com> escreveu:

**Comment by wmcbrine** [comment]
The patch is in the git repos now. If you need me to build you a binary, please email me privately. (Eventually I'll do a full new version release that includes the changes.)
