### ISSUE TITLE
Windows 10 RedStone 1

### ISSUE THREAD

**Issue by apometron** [wmcbrine/MultiMail#5]
Hello! =D

I cant unpack the messages in Windows 10 RedStone 1.

"No files uncompresed - check archiver config"

Strange, because the message packet is packed in ZIP format.

Help, please? =)

Thanks a lot !!! =)

**Comment by apometron** [comment]
We are on the RedStone 3 and yet no new version of MultiMail. I cant read BBS msgs because of this bug. Please, update!!! =(((( Are you leave Windows 10 users in the black? It is a shame!!!

**Comment by wmcbrine** [comment]
As discussed in email, there isn't much here to go on. I did give you a suggestion, which you didn't comment on. I'll repeat it here: '... apparently, PowerShell by default restricts one process from launching another (although I only saw this discussed in the context of scripts). The workaround for this was to enter the command "set-executionpolicy unrestricted" before starting the script. Perhaps that will also let MultiMail start Unzip?'

Let me pull that out one more time for emphasis:

set-executionpolicy unrestricted

Please try that before running MultiMail, and see if it helps.

I should add that I've so far been unable to reproduce your problem, although my Windows development environment situation is pretty dire at the moment (hoping to fix soon).

**Comment by apometron** [comment]
I dont use PowerShell, I do use Take Command 11 x64.

F:\>tcc
Copyright 2010  Rex Conn & JP Software Inc.  All Rights Reserved
Registered to Judy Wesling - 1 System License

[F:\]

Do You understand? This is my environment which I run from since eras.

https://i.imgur.com/9aBm346.png

https://i.imgur.com/dQOXdeC.png

Do You see, sir?

I run an alternative command processor.

I just do not use Power Shell.

All my applications run from Take Command 11 x64.

Please, consider this.

With respect,
Apometron
http://about.me/apometron

**Comment by wmcbrine** [comment]
OK, you should've mentioned that at the beginning. Try without it? And / or try updating it, since that version is really old.

**Comment by apometron** [comment]
I lost my msg packages because of a corruption of my  SSD.

I will try update Take Command and see what  happens.

I will report the results here later.

Thanks !!!!

**Comment by apometron** [comment]
Fantastic, Will. I changed to TCC LE 14.0 and now MultiMail is working with packages again. Great!!!!! =DDD Very thanks !!!! =DDD But and the new features? Do it will happen? A new release would be good !!! =DDD
