### ISSUE TITLE
compress command (in creating replies) is not passed full path to file to compress

### ISSUE THREAD

**Issue by askpatrickw** [wmcbrine/MultiMail#8]
The path to the file to add to the archive is not passed and we're not in the right directory so I replaced zipCompressCommand with a batch file in mmail.rc

    zipCompressCommand: [YOUR_PATH]\multimail\mm_zip.cmd

```
@echo off
cd [YOUR_PATH]\multimail\work*
..\zip -jkq %1 .\upwork\%2
```

This seems like it will work fine as long as there are not >1 workNNN directories.

**Comment by wmcbrine** [comment]
As with your other issue, I'm not seeing the behavior you describe.

**Comment by wmcbrine** [comment]
...
